### ISSUE TITLE
应该要登陆之后才能看到其他议委的个人信息

### ISSUE THREAD

**Issue by Liby99** [yang991178/SMS_Council#1]
不然这些信息就公开了

**Comment by yang991178** [comment]
学生是需要知道代表他们的议委的联系方式的，这些信息议事会的公众号也会推。但是得加个robots.txt防搜索引擎倒是真的。

**Comment by yang991178** [comment]
突然想起来因为没做SEO所以爬虫也抓不到这些动态加载的信息，所以就现在这样就好【逃
